### PR TITLE
core: simplify the commit update & add config to insert emoji at the end of the commit

### PR DESCRIPTION
**Pull request by nabondance**
This is a proposal for an issue I'm often facing with my team:

We have a commit nomenclature like this: 
`[<issue key>] <emoji> <Summary>`
So when writing the commit message, we want to insert the emoji not at the beginning, but where we are writing (`[<issue key>] HERE`)
I tried to find a way to input the emoji where the cursor is in the inputBox but it didn't worked.
The workaround is to update the inputBox by placing the emoji at the end of it.
I created a new configuration to handle both possibilities (prefix and suffix).

More information:
- I haven't found a CONTRIBUTING file, I tried to contribute as usually
- It's the first time I develop a vs-code extension
- I refactored the code to avoid adding multiple if
- I translated with online tools and I'm not sure at all about the translations

Do you need more information ?
Please feel free to tell me how to improve it

### CODE REVIEW

**Comment by nabondance** [comment]
Hi @seatonjiang ,
I hope you are going well, have you been able to have a look at this PR ?

Please tell me if there's anything wrong with it

Regards,

**Comment by seatonjiang** [comment]
Hi @nabondance ,

I apologize for getting back to you so late, I saw this PR a few weeks ago but didn't have time to test it at the time because of work, now I'm testing it.

**Comment by nabondance** [comment]
Hi @seatonjiang ,
No worries at all, thank you for your time

**Review by seatonjiang — APPROVED** [review]

**Comment by seatonjiang** [comment]
Hi @nabondance ,
Thank you for PR.

**Pull request merged**
